import type { Metadata } from "next";
import "./globals.css";
import Socials from "@/components/social";
import Nav from "@/components/nav";
import Email from "@/components/email";

export const metadata: Metadata = {
  title: "Gaurav Deshmukh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">
        <Nav />
        <Socials />
        <main className="h-full snap-y">{children}</main>
        <Email />
      </body>
    </html>
  );
}
