import type { Metadata } from "next";
import "./globals.css";
import Socials from "@/components/social";
import Nav from "@/components/nav";
import Email from "@/components/email";

export const metadata: Metadata = {
  title: "Gaurav Deshmukh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body className="overflow-x-hidden">
        <Nav />
        <Socials />
        <main className="h-full snap-y">{children}</main>
        <Email />
      </body>
    </html>
  );
}
